# https://github.com/denopendabot
name: Denopendabot (without GitHub App)
on:
  create:
  schedule:
    - cron: "34 19 * * 1-5"
jobs:
  denopendabot:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: denopendabot/dependabot-action@master
